### ISSUE TITLE
Fee Schedule Proposal - Price of LTM too high.

### ISSUE THREAD

**Issue by jonathanbahai** [BitShares-Committee/Instructions#1]
https://github.com/BitShares-Committee/Instructions/blob/master/usd-denominated-fees/fee-schedule-proposed-by-xeroc.py

```
           "account_upgrade": {
               "membership_annual_fee": 20,
               "membership_lifetime_fee": 150
           },
```

The LTM fee seems too high given the scope of features and benefits offered. I think at the 6 month review we can consider reassessing and then raising it accordingly. However at this stage, I would recommend something along the lines of $100 or less. 

More specific I would recommend $97 for lifetime and $17 for annual.

**Comment by xeroc** [comment]
One an account upgrades, he essentially opts-out of the referral program and nothing more goes to the registrar. The idea that I was following was to encourage users to stay basic member and have registrars benefit from it as long as possible, which is why the transfer and trading fees are reduced.

You can't have both, reduced fees for transfers and upgrades **and** keep the referral program alive!

**Comment by bitcrab** [comment]
you can keep it at current level, about $68, no need to raise.

**Comment by xeroc** [comment]
> you can keep it at current level, about $68, no need to raise.

I don't see your argument here. We can of course keep everything as it is. But we can also change it just "because". Or because they make "more" sense to "someone"!

Do we want people to STAY in basic membership or do we want them to UPGRADE to premium? Do we want to have referral businesses to earn from transfers, or from upgrades?

**Comment by jonathanbahai** [comment]
> One an account upgrades, he essentially opts-out of the referral program and nothing more goes to the registrar.

The issue with that is that with profits driven down to lower levels for the transactions, it makes the profitability per refer much less. The return on the user could take a very long time compared to the amount spent to bring that user to the network. So it disincentivized the promotion.

If however LTM is more accessible, and the average adoption of LTM stays ahead of the average users referred that are not becoming LTM, then it can offset the numbers and possibly make promotion profitable. 

I think this demand for LTM will grow as possibly new features or benefits are introduced to LTM only as has been suggested by some.

**Comment by xeroc** [comment]
> The issue with that is that with profits driven down to lower levels for the transactions, it makes the profitability per refer much less. The return on the user could take a very long time compared to the amount spent to bring that user to the network. So it disincentivized the promotion.

If you consider only one user, then yes. Considering that with this approach you could  bring in MORE users compared to now, it still works out.

> If however LTM is more accessible, and the average adoption of LTM stays ahead of the average users referred that are not becoming LTM, then it can offset the numbers and possibly make promotion profitable.

For a marketing business, how much would they ask for to bring you one loyal user? If we can figure that out, then we know what price we should set.

> I think this demand for LTM will grow as possibly new features or benefits are introduced to LTM only as has been suggested by some.

Indeed

**Comment by jonathanbahai** [comment]
> For a marketing business, how much would they ask for to bring you one loyal user? If we can figure that out, then we know what price we should set.

For a competitive CPA (cost per action) campaign if they can earn $1 per action. That means they should be able to average in this case $1 profit on every account that signs up. Their total marketing cost should not exceed 30% of that on a well optimized campaign. 

Based on this for a promoter to consider this product to be worth promoting, assuming they get $77 on every LTM based on my recommendation, that means on a per/month basis they need to see 1 in 77 signups to Bitshares upgrade to LTM. 

This means that they would have a budget of roughly $23 per 77 signups. Assume a 1% conversion rate on traffic, they would need to send 7700 visitors. A Facebook campaign that is $1 CPM would come to about $8. These are rather optimistic numbers without test campaigns. It could take 3X the amount to get even one signup.

While others will bring them some ongoing profits from transctions, as I said, in order to cover the cost of the campaign it would not provide any immediate revenues. It would be considered a value add bonus. 

The $97 buy in for targeting something like the trader market perhaps with what produces we have would be a reasonable sell. Fav already did a test in the first months of the program and found the conversion to be in the neighbourhood of $0.25 per user. We have improved a lot of things since then though, but that was also based on close to the current rates offered for LTM. Going to $150 would double it and thus reduce conversions significantly making any of these calculations more unlikely.

With this considered, a vesting period of 30 to 60 days would make sense for the fee back on LTM.

**Comment by gileadmcgee** [comment]
I also think $150 is too high for LTM.  $97 could work out very well.  Data is it possible to run your above numbers on the current price of about $68.  Would that still allow referrers to be profitable?

**Comment by jonathanbahai** [comment]
I would like to change my recommendation to be $89 for LTM if we we are looking at the base refer network cut being reduced to 10%. This would effectively make the total payout to refers $80.

**Comment by BhuzOr** [comment]
I don't think the fee is too high considering what we are trying to acheve with all this fee schedule.
