### ISSUE TITLE
Fee-schedule: Cancellation fee should smaller than order creation fee

### ISSUE THREAD

**Issue by clayop** [BitShares-Committee/Instructions#3]
https://github.com/BitShares-Committee/Instructions/blob/master/usd-denominated-fees/fee-schedule-proposed-by-xeroc.py#L324

If order cancellation fee equals to creation fee, it means no refund, which contradict the original idea of refund when cancellation.

**Comment by xeroc** [comment]
agreed
https://github.com/BitShares-Committee/Instructions/commit/4b66bc648aa625c6124e2ab78953f9b749cd98c5
