### ISSUE TITLE
Conversation between Bhuz, xeroc, abit, mindphlux

### ISSUE THREAD

**Issue by mindphlux1** [BitShares-Committee/Instructions#5]
Summary:

LTM fee shall be set to $120 instead of $150 ($150 considered too high for some), to compensate the reduced income for the ref program due to the lowered tx fee. LTM fee shall be raised regularly with each new feature that comes (ie. Bond Market, MAS). Advanced features are LTM only.

Also, as a promotion action with each new feature, committee can run a discount on LTM fee, like $99 for a limited time to promote the use of a new feature.

**Comment by xeroc** [comment]
_confirmed_
